// Generated Code But Editable.
// Format The Code with `go fmt` or something and edit it manually to use it.
//
// Generated by: api-to-go (https://github.com/nkmr-jp/api-to-go).

package jsonplaceholdertypicodecom

// TodosGetQuery is the HTTP Request Query Parameter.
//
//	Request: GET https://jsonplaceholder.typicode.com/todos?userId=1
//	Docs:    https://jsonplaceholder.typicode.com/
type TodosGetQuery struct {
	UserID string `json:"userId"`
}
