// Generated Code But Editable.
// Format The Code with `go fmt` or something and edit it manually to use it.
//
// Generated by: api-to-go (https://github.com/nkmr-jp/api-to-go).

package jsonplaceholdertypicodecom

// TodosPost is the HTTP Response Body.
//
//	Status:  201 Created
//	Request: POST https://jsonplaceholder.typicode.com/todos
//	Docs:    https://jsonplaceholder.typicode.com/
type TodosPost struct {
	ID int `json:"id"`
}
