// Generated Code But Editable.
// Format The Code with `go fmt` or something and edit it manually to use it.
//
// Generated by: api-to-go (https://github.com/nkmr-jp/api-to-go).

package jsonplaceholdertypicodecom

// TodosPostBody is the HTTP Request Body Parameter.
//
//	Request: POST https://jsonplaceholder.typicode.com/todos
//	Docs:    https://jsonplaceholder.typicode.com/
type TodosPostBody struct {
	UserID    int    `json:"userId"`
	ID        int    `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}
