#!/bin/bash

TEST_FILE=$(basename ${BATS_TEST_FILENAME})
DOC_PATH="docs/$TEST_FILE.md"
doc(){
  echo "$1" >> "$DOC_PATH"
}

init_doc(){
  rm -f "$DOC_PATH"
  doc "Generated by $TEST_FILE . last modified $(date '+%Y/%m/%d %T')"
}

write_doc_details(){
  doc
  doc "Command:"
  doc
  doc "\`\`\`sh"
  doc "$COMMAND"
  doc "\`\`\`"
  doc
  doc "Output:"
  doc
  if jq -e . >/dev/null 2>&1 <<< "$output"; then
    doc "\`\`\`sh"
    doc "$(echo "$output" | jq)"
    doc "\`\`\`"
  else
    doc "\`\`\`sh"
    doc "$output"
    doc "\`\`\`"
  fi
}