# .github/workflows/publish.yml
# Manual workflow to publish to npm (for retrying failed publishes)

name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - name: Publish
        run: |
          npm install -g npm@latest
          git config --global user.email "nkmr.git@gmail.com"
          git config --global user.name "nkmr-jp"
          npm run sync-version
          npm publish --access=public --provenance
          git push
