# .github/workflows/release.yml

name: Release
on:
  push:
    branches:
      - master
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Install yq
        run: |
          pip install --break-system-packages yq
          jq --version
          yq --version
      - name: Install gitmoji-semver
        run: |
          git clone https://github.com/nkmr-jp/gitmoji-semver -b v2.0.5
      - name: Generate semantic-release configs
        working-directory: ./gitmoji-semver
        run: |
          make scaffold F=../.semver.yml O=..
      - name: Release
        working-directory: ./.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
      - name: Publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ''
        run: |
          rm -f "$NPM_CONFIG_USERCONFIG"
          git config --global user.email "nkmr.git@gmail.com"
          git config --global user.name "nkmr-jp"
          npm run sync-version
          npm publish --access=public --provenance
          git push
